### ISSUE TITLE
No main file(s) specified in bower.json

### ISSUE THREAD

**Issue by macu** [instructure/ic-ajax#13]
Hi, some build tools that work with Bower inspect the bower.json file for main files. For example, [gulp-bower-files](https://www.npmjs.org/package/gulp-bower-files) throws the following exception if ic-ajax is a dependency listed in bower.json:

_The bower package ic-ajax has no main file(s), use the overrides property in your bower.json_

The [Bower spec](https://docs.google.com/document/d/1APq7oA9tNao1UYWyOm8dKqlRP2blVkROYLZ2fLIjtWc/edit#heading=h.4pzytc1f9j8k) suggests adding a section to the bower.json to indicate the intended endpoints of the library.

Keep up the good work!

**Comment by rwjblue** [comment]
Broccoli also looks for a `main` in the `bower.json`.

**Comment by ryanflorence** [comment]
_this property intentionally left blank_

I do not know what to put there.

I want the main file to be `lib/main.js`, but then none of these tools you're using will understand ES6. I could point to one of the `dist` main files but that doesn't help either.

Additionally, the bower spec is still in debate about what "main" even means. I was involved in that conversation earlier but it quickly got frustrating and ridiculous:

bower/bower#46
bower/bower#263
bower/bower#935
bower/bower.json-spec#6
bower/bower.json-spec#7
bower/bower.json-spec#8
bower/bower.json-spec#9

What I'm waiting for is a `moduleType` property that lets me specify what the main file is for each module type until this miserable module mess is over and package managers like http://jspm.io handle the module crap for us.

The current implementation doesn't let me do that (as far as I can tell).

https://github.com/bower/bower.json-spec/issues/10

> Broccoli also looks for a main in the bower.json

Why does broccoli care? Or do you mean some tool built with broccoli?

So anyway ... your tools need to ask the user where to find the main file because _I have no idea which one you actually want_.

**Comment by macu** [comment]
I agree that the current conventions are unclear and inconsistent.

If you look at "[consuming a package](https://github.com/bower/bower#consuming-a-package)", `bower list --paths` is supposed to give a consistent set of endpoints, like `bower_components/library_name/index.js` but in practise the developer must inspect the contents of the package directories to find the desired files, because little or nothing is available at `index.js`. Even jQuery is listed at `bower_components/jquery/dist/jquery.js`, differing from the example in the Bower README.

If you look at [the bower.json of a library like Bootstrap](https://github.com/twbs/bootstrap/blob/master/bower.json), multiple files are listed as main.

I think it would be acceptable to list each of the various main.js files in the ic-ajax/dist directory, as the developer is going to have to inspect the listing and choose one anyway. This is valid according to the spec.

**Comment by macu** [comment]
Anyway, we can wait but "this is not supported because the spec will change" is self-defeating. Because Bower is so widely used, any improvements are likely to be backwards-compatible in the short term, giving time for developers to upgrade their bower.json files.

**Comment by ryanflorence** [comment]
An array for "main" is not only ridiculous but its pretty clear that its going away: bower/bower.json-spec#6

Your tools need to solve this until bower has a clue what `main` means. I don't want to cause accidental problems with tools that think they understand my main script but really don't.

Its not self-defeating.
- the npm package has a main entry that works perfectly with browserify
- the amd build has to be configured as a package, and package configs allow you to specify the main script, if your tool is doing this it should simply prompt that it didn't find a main entry and ask you where it is.
- global builds require a config for concat, or script tag includes, that the user controls anyway, and again, if a tool is doing this it should prompt for the path.

Providing `main` when there is no agreement (or defacto agreement) on what it means will only lead to different problems for different tools. By not providing a `main` then it is the same problem for all tools. If I'm going to cause a problem, I want to cause the same problem for everybody.

**Comment by macu** [comment]
Good enough. I appreciate the clarification.

**Comment by ryanflorence** [comment]
it is a frustrating issue for me as well :), back when I was working on https://github.com/rpflorence/bower-import

https://github.com/rpflorence/bower-import/blob/master/index.js#L85-L100

**Comment by okfro** [comment]
It's a frustrating issue for me as well. Ignoring the debate over what "main" means, it seems clear that someone has to communicate somewhere which are the consumable files in the project? Which ones are required? Which ones are optional? Which ones are for development vs production?

Since there is no consistency in the bower package universe in folder structure or naming conventions, there is no other way to deterministically know which files are required and where they are located. 

As just one data point: if you look at the issue log for gulp-bower-files, https://github.com/ck86/gulp-bower-files/issues, you can see the extent to which developers find this confusing.
